### ISSUE TITLE
InputFormatter Digits Only

### ISSUE THREAD

**Issue by cenezoic123** [iamvivekkaushik/OTPTextField#1]
I hope inputFormatters property in OTPTextField will be added, 
so that we can restrict what type of characters that user can input in the textfield .

ex.
inputFormatters: [WhitelistingTextInputFormatter.digitsOnly],

**Comment by iamvivekkaushik** [comment]
Hi, you can achieve this by using the keyboard type property in the constructor. 

```
this.keyboardType = TextInputType.number
```
