### ISSUE TITLE
Called on null issue after flutter 2.0 upgrade

### ISSUE THREAD

**Issue by selvas1998** [iamvivekkaushik/OTPTextField#11]
while typing text or numbers in OTP text field, called on null issue was arising after my project upgraded into flutter 2.0.1.
I think it was related to null safety. I hope this issue has been fixed as soon as possible.
![Screenshot (18)](https://user-images.githubusercontent.com/44501196/110199943-06820f80-7e81-11eb-8ad9-773ce67a72e4.png)

**Comment by iamvivekkaushik** [comment]
I've migrated the project to null-safety. Update to the latest version. Please close this issue after confirming your issue Is fixed.

**Comment by selvas1998** [comment]
Thank you for your reponse. Now, the issue is fixed. Keep it up.
