### ISSUE TITLE
handling Custom keyboard

### ISSUE THREAD

**Issue by Pranav108** [iamvivekkaushik/OTPTextField#19]
I want to use this with my custom Keyboard but didn't find something like `controller` as available in `TextField` widget to use here.
<img src="https://user-images.githubusercontent.com/56934594/147553493-385af982-830d-4bf7-9c03-de738bcb431a.png" width="350"/>
How can I implement that here?

**Comment by iamvivekkaushik** [comment]
Hi,

This feature is currently not available in this library. I'm not sure whe
I'll be able to get time to work on it. If you can implement it yourself
you're welcome to fork it and raise a PR.

Thanks

**Comment by iamvivekkaushik** [comment]
This is now supported in the latest version.
