### ISSUE TITLE
How to trigger OTPTextField to use the errorBorderColor / disabledBorderColor?

### ISSUE THREAD

**Issue by timkanurmamatov** [iamvivekkaushik/OTPTextField#25]
how to trigger OTPTextField to use the errorBorderColor / disabledBorderColor?

_Originally posted by @aulia-rosyida in https://github.com/iamvivekkaushik/OTPTextField/issues/2#issuecomment-1034918465_

**Comment by JulianBissekkou** [comment]
This will be fixed with #27
