### ISSUE TITLE
OTPTextField' isn't a function.\nTry correcting the name to match an existing function, or define a method or function named 'OTPTextField

### ISSUE THREAD

**Issue by 5M06** [iamvivekkaushik/OTPTextField#38]
Throwing multiple issues.

**Error One:**
[{
"resource": "/d:/mobile_apps_source/ppnnews/lib/components/OTPDialog.dart",
"owner": "_generated_diagnostic_collection_name_#0",
"code": {
"value": "ambiguous_import",
"target": {
"$mid": 1,
"external": "https://dart.dev/diagnostics/ambiguous_import",
"path": "/diagnostics/ambiguous_import",
"scheme": "https",
"authority": "[dart.dev](http://dart.dev/)"
}
},
"severity": 8,
"message": "The name 'OTPTextField' is defined in the libraries 'package:nb_utils/src/widgets/otp_text_field.dart (via package:nb_utils/nb_utils.dart)' and 'package:otp_text_field/otp_field.dart'.\nTry using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.",
"source": "dart",
"startLineNumber": 188,
"startColumn": 17,
"endLineNumber": 188,
"endColumn": 29
}]

**Error Two:**
[{
"resource": "/d:/mobile_apps_source/ppnnews/lib/components/OTPDialog.dart",
"owner": "_generated_diagnostic_collection_name_#0",
"code": {
"value": "invocation_of_non_function",
"target": {
"$mid": 1,
"external": "https://dart.dev/diagnostics/invocation_of_non_function",
"path": "/diagnostics/invocation_of_non_function",
"scheme": "https",
"authority": "[dart.dev](http://dart.dev/)"
}
},
"severity": 8,
"message": "'OTPTextField' isn't a function.\nTry correcting the name to match an existing function, or define a method or function named 'OTPTextField'.",
"source": "dart",
"startLineNumber": 188,
"startColumn": 17,
"endLineNumber": 188,
"endColumn": 29
}]
--
Please help

![Screenshot (53)](https://user-images.githubusercontent.com/60471853/187088983-cf52b952-305f-460f-b8fb-d718ccb9ddf3.png)
![Screenshot (54)](https://user-images.githubusercontent.com/60471853/187088988-ea8848ec-f163-4528-b5ef-a38ff63a9adb.png)
![Screenshot (52)](https://user-images.githubusercontent.com/60471853/187088992-21b2e420-d9a5-4f7b-8b87-06a2500705cf.png)

**Comment by iamvivekkaushik** [comment]
You are using another import `nb_utils` which is causing a conflict. Use the `as` keyword for one of the import.

**Comment by 5M06** [comment]
> You are using another import `nb_utils` which is causing a conflict. Use the `as` keyword for one of the import.

Thank You so much fast response. But is there any guides??? if you have link can you give it me? Extremely sorry new to flutter.

**Comment by iamvivekkaushik** [comment]
https://stackoverflow.com/questions/56884514/how-to-resolve-package-conflict-in-flutter

**Comment by 5M06** [comment]
Solved the issue. Thank You.

**Comment by 27thstein** [comment]
Hello, can you please give me insight on the changes that fixed the issue? I'm facing the same issue
