### ISSUE TITLE
Deleting problem before finishing

### ISSUE THREAD

**Issue by federicodesia** [iamvivekkaushik/OTPTextField#8]
Several libraries do not allow deleting and going back to the previous TextInput, this solves it very well.

Example of the problem:
In an OTPTextField with length: 4, typing the 4 digits and then deleting works correctly. But trying to delete without reaching the fourth TextField it just doesn't go back to the previous TextField.

Tested on Android.

**Comment by iamvivekkaushik** [comment]
Hi @federicodesia, thanks for pointing that out. I will try to fix the issue you're having once I get some free time on my hand. If you have a solution you're welcome to create a pull request.
